// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aslnlfkkjpdipcjzqalb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbG5sZmtranBkaXBjanpxYWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzIyMTEsImV4cCI6MjA2MTAwODIxMX0.JpJZ5779HbnCF8N-ViwO4o-L5RdP_qbE6FsB_ChED5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);